C version added
GaryHughes/Exchange pull request #17
Opened 2020-05-29 07:57 UTC by gnbond

Added a C version.  Optimized Part 2 version runs in about half a second.

I've used "git subtree" to include a unit-testing framework, I don't know how this will work out....

2020-05-29 22:44 UTC, GaryHughes commented on Part 1/c_solution/order_book.c
> +        strlcpy(ob->instrument, instrument, INSTRUMENT_SIZE);
strlcpy requires #include <bsd/string.h> on linux where the builds happen.

2020-05-29 22:45 UTC, GaryHughes commented on Part 1/c_solution/Makefile
> +	$(CC) $(CFLAGS) -o $@ $(OBJS)
strlcpy requires -lbsd on linux where the builds happen

2020-05-29 22:46 UTC, GaryHughes commented on Part 2/c_solution/Makefile
> +	$(CC) $(CFLAGS) -o $@ $(OBJS)
strlcpy requires -lbsd on linux where the builds happen

2020-05-29 22:48 UTC, GaryHughes commented on Part 2/c_solution/order_book.c
> +
strlcpy requires #include <bsd/string.h> on linux where the builds happen

2020-05-29 22:49 UTC, GaryHughes requested changes
Some small changes required to compile on linux.

2020-05-30 01:34 UTC, gnbond commented
Committed a change to use strncpy() instead.  Builds on Ubuntu.

2020-05-30 01:35 UTC, merged